item: 2 #1 = sword, 2 = arc, 3 = hoe
locations:
  spawn:
    base1:
      x: 0.5
      y: 5.0
      z: 7.0
      p: 0.0
      ya: 0.0
    base2:
      x: 0.5
      y: 5.0
      z: 7.0
      p: 0.0
      ya: 0.0
    lobby:
      x: 0.5
      y: 4.0
      z: 0.0
builder: "?"
    